### ISSUE TITLE
DB connection issue

### ISSUE THREAD

**Issue by Vedgaurav** [Vedgaurav/gvs#2]
Check these three classes statement.connection is giving error

AddressIdGenerator
YatraMemRegIdGenerator
DevoteeIdGenerator

Suggestion: Can we use JPARepository for this database operation

**Comment by Saurav109677** [comment]
we need id in different format like 
HLZ23XXX1
HLZ23XXX2
HLZ23XXX3

for this created a generator

**Comment by Vedgaurav** [comment]
Changes done using jpa repo method
